server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedulesystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
  mvc:
    pathmatch:
      #?????swagger?
      matching-strategy: ant_path_matcher

  #????
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
